sudo: required
language: go
go:
  - "1.12.15"

before_install:
  - export GOPATH=$HOME/go
  - export PATH=$HOME/usr/local/go/bin:$GOPATH/bin:$PATH
  - mkdir -p $GOPATH/src/github.com/ovn-org
  - mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/ovn-org/ovn-kubernetes
  - cd $GOPATH/src/github.com/ovn-org/ovn-kubernetes

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

jobs:
  include:
    - stage: coverage
      script:
        - pushd go-controller
        -    COVERALLS=1 make check
        -    $(go env GOPATH)/bin/gover
        -    $(go env GOPATH)/bin/goveralls -service=travis-ci -coverprofile=gover.coverprofile
        - popd

